<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='UTF-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marie Pichault Sophrologue</title>
    <link rel="icon" type="image/x-icon" href="./favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png">
    <link rel="manifest" href="./site.webmanifest">
    <link rel="mask-icon" href="./safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
    <link rel="stylesheet" href="./assets/css/common/normalize.css">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
</head>
<body class="container">
    <header class="header">
        <h1 class="header__h1">Marie Puchault Sophrologue</h1>
        <p class="catch"><q>En te levant le matin, rappelle toi combien est
                précieux le privilège de vivre, de respirer, 
                d'être heureux.</q> de Marc Aurèle</p>
    </header>
    <nav class="navbar">
        <p>Menu</p>
        <input class="navbar__toggle" type="checkbox" />
        <label class="navbar__btn" for="navbar__toggle">
          <span></span>
        </label>
        <ul class="navbar__nav">
            <li><a href="index.php?action=welcome">Accueil</a></li>
            <li><a href="index.php?action=about">A propos</a></li>
            <li><a href="index.php?action=blog">Galerie</a></li>
            <li><a href="index.php?action=services">Mes services</a></li>
            <li><a href="index.php?action=test">Témoignages</a></li>
        </ul>
    </nav>
    <main>
        <?= $content ?>
    </main>
</body>
</html>