<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='UTF-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marie Puchault Sophrologue</title>
    <link rel="icon" type="image/x-icon" href="./favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png">
    <link rel="manifest" href="./site.webmanifest">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" /> 
    <link rel="stylesheet" href="./assets/css/common/normalize.css">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
    integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
    integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
    crossorigin=""></script>
</head>
<body class="container">
    <header class="header">
        <h1 class="header__h1">Marie Puchault Sophrologue</h1>
        <p class="catch"><q>En te levant le matin, rappelle toi combien est
                précieux le privilège de vivre, de respirer, 
                d'être heureux.</q> de Marc Aurèle</p>
    </header>
    <nav class="navbar">
        <p>Menu</p>
        <input class="navbar__toggle" type="checkbox" />
        <label class="navbar__btn" for="navbar__toggle">
          <span></span>
        </label>
        <ul class="navbar__nav">
            <li><a href="index.php?action=Welcome">Accueil</a></li>
            <li><a href="index.php?action=Services">Mes services</a></li>
            <li><a href="index.php?action=Test">Témoignages</a></li>
            <li><a href="index.php?action=About">A propos</a></li>
        </ul>
    </nav>
    <main>
        <?= $content ?>
    </main>
    <footer class="footer">
        <section class="footer__contact">
            <address>
                <h2>Contactez-moi</h2>
                <?= $infos[0]['street'] ?><br> <?=  $infos[0]['city'] ?><br><br>
                <a href="mailto:<?= $infos[0]['mail'] ?>"><?=  $infos[0]['mail'] ?></a><br>
                <a href="tel:+33<?= preg_replace("/[^0-9]\./", '', $infos[0]['tel']) ?>"><?=  $infos[0]['tel'] ?></a>
            </address>
            <div id="map" class="footer__contact__map"></div>
        </section>
    </footer>
    <script type="module" src='./assets/js/streetmap.js'></script>
</body>
</html>