<?php if (isset($articles) && !empty($articles)): ?>
<section class="hang">
    <article>
        <?php if (isset($articles[1]['postSrc'])): ?>
        <img src="<?php echo htmlentities($articles[1]['postSrc']) ?>" alt="<?= htmlentities($articles[1]['postImgName'])?>" />
        <?php endif; ?>
        <div>
        <?= $articles[1]['postCont'] ?>
        </div>
    </article>
    <article>
        <?php if (isset($articles[0]['postSrc'])): ?>
        <img src="<?php echo htmlentities($articles[0]['postSrc']) ?>" alt="<?= htmlentities($articles[0]['postImgName'])?>" />
        <?php endif; ?>
        <div>
        <?= $articles[0]['postCont'] ?>
        </div>
    </article>
</section>
<?php endif; ?>