<h2 class="title">Quelques Témoignages</h2>
<?php if (isset($articles) && !empty($articles)): ?>
<section class="test">
<?php foreach($articles as $index => $article): ?>
    <article>
        <?= $article['postCont'] ?>  
        <?php if (isset($article['postSrc'])): ?>
            <img src="<?php echo htmlentities($article['postSrc']) ?>" alt="<?= htmlentities($article['postImgName'])?>" />
        <?php endif; ?>
    </article>
<?php endforeach; ?>
</section>
<?php endif; ?>
