<section class="about">
    <h2>Mes services</h2>
    <p>Qui est concerné ? les salariés souffrant de dépression ou de burn out liés aux exigences de rendement toujours plus importants. Les entreprises subissant de plus en plus l’absentéisme créant ainsi un état de tension grandissant.</p>
    <p>Temps de séances estimé entre 1 h et 1 h 30 et le nombre de séances varie entre 8 et 10 séances en fonction de la nature de la problématique et du mieux être au fur et à mesure des séances.</p>
</section>
<section class="card">
    <article class="card__ind">
        <h3>Les séances individuelles chez moi :</h3>
        <ul>
            <li> Un temps d’introspection ou micro analyse pour bien évaluer la problématique.</li>
            <li> Un temps de relaxation avec la séance en elle-même assis ou allongé.</li>
            <li> Un temps de paroles sur le ressenti de la séance.</li>
        </ul>
    </article>
    <article class="card__col">
        <h3>Proposition de séances de groupe au sein d’une association, d’une entreprise :</h3>
        <ul>
            <li> Explication des séances de sophrologie et déroulé des séances</li>
            <li>Ressenti des séances</li>
        </ul>
    </article>
</section>
