<article class="homeServices">
    <p class=homeServices__p1>Vous avez une problématique de vie (stress, anxiété, insomnie, fatigue).
    Vos projets vous paraissent inaténiables.
    Vos pensées sont négatives et accaparantes.</p>
    <img class="homeServices__img"  src="./assets/images/jasper-doornbos-EilGUQX9ELI-unsplash.jpg">
    <p class="homeServices__p2">Je vous propose la détente, le lacher prise et une meilleure connaissance de soi.</p>
</article>
<div id="my_osm_widget_map"></div>
<section class="contact">
    <h2>Contactez-moi</h2>
    <address>
        3 rue de la vigne <br> 35460 St Etienne en Cogles (Maen Roch)<br>
        <a href="mailto:marie.puchault@outlook.fr">marie.puchault@outlook.fr</a><br>
        <a href="tel:+33617712335">06.17.71.23.35</a>
    </address>
</section>
<script type="module" src='./assets/js/mapbox.js'></script>

