<?php if (isset($articles) && !empty($articles)) : ?>
<?php foreach($articles as $index => $article): ?>
<?php if ($index === 0): ?>
<section class="intro">
    <?php if (isset($article['postSrc'])): ?>
    <img src="<?php echo htmlentities($article['postSrc']) ?>" alt="<?= htmlentities($article['postImgName'])?>" />
    <?php endif; ?>
    <article>
    <?= $article['postCont'] ?>
    </article>
</section>
<section class="card">
<?php else: ?>
    <article>
        <?php if (isset($article['postSrc'])): ?>
        <img src="<?php echo htmlentities($article['postSrc']) ?>" alt="<?= htmlentities($article['postImgName'])?>" />
        <?php endif; ?>
        <?= $article['postCont'] ?>
    </article>
<?php endif; ?>
<?php endforeach; ?>
</section>
<?php endif; ?>


