<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset='UTF-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex">
    <title>Marie Puchault Sophrologie</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> <link rel="stylesheet" href="./assets/css/common/normalize.css">
    <link rel="stylesheet" href="./assets/css/common/normalize.css">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="icon" type="image/x-icon" href="./favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png">
    <link rel="manifest" href="./site.webmanifest">
    <script src="https://cdn.tiny.cloud/1/xncrnej93crwth4roved3pt5h6u8vha9reox92mjtd4hvigr/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript" src="./assets/js/tinymce.js"></script>
</head>
<body class="container">
    <header class="header">
        <h1 class="header__h1">Marie Puchault Sophrologie</h1>
        <?php if(isset($_SESSION) && !empty($_SESSION['email'])): ?>
            <div class="header__button">
                <a href="index.php?action=close">Logout</a>
            </div> 
        <?php else: ?>
            <div class="header__button">
                <a href="index.php?action=auth&q=connect">Login</a>
            </div>
        <?php endif ?>
    </header>
    <main>
        <?= $content ?>
    </main>
</body>
</html>