<h1><?= $article[0]['postTitle'] ?></h1>
<em><?= $article[0]['postDesc'] ?></em>
<?= $article[0]['postCont'] ?>

<?php if (isset($article[0]['postSrc'])): ?>
<img src="<?php echo htmlentities($article[0]['postSrc']) ?>" alt="<?= htmlentities($article[0]['postImgName'])?>" />
<?php endif; ?>


<p class="back"><a href="index.php?action=auth&q=<?= htmlentities($_GET['q'])?>&opt=getAll" >Retour</a></p>