<section class="viewer">
    <article class="viewer__text">
        <?= $article[0]['postCont'] ?>
    </article>
    
    <?php if (isset($article[0]['postSrc'])): ?>
    <img src="<?php echo htmlentities($article[0]['postSrc']) ?>" alt="<?= htmlentities($article[0]['postImgName'])?>" />
    <?php endif; ?>
</section>

<p class="back"><a href="index.php?action=auth&q=<?= htmlentities($_GET['q'])?>&opt=getAll" >Retour</a></p>