<div class="content">
    <h2 class="content__title">Le contenu pour la rubrique des <?= (substr($_GET['q'], 0, -5) === "test" ) ? "témoignages" : "services" ?></h2>
    <p class="content__addRow"><a href="index.php?action=auth&q=<?= $_GET["q"]?>&opt=addArticle">Ajouter du contenu</a></p>
    <table>
        <thead>
            <tr>
                <tb>Page d'accueil</tb>
                <td>Titre</td>
                <td>Description</td>
                <td>Contenu</td>
                <td>Crée le</td>
                <td>Image</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data['article'] as  $article): ?>
            <tr>
                <td><input type="checkbox" value="<?= $article['postId'] ?>"></td>
                <td><?=$article['postTitle']?></td>
                <td><?=$article['postDesc']?></td>
                <td><?=substr($article['postCont'], 0, 30).'...'?></td>
                <td><?=$article['postDate']?></td>
                <td><?php echo (isset($article['tb_pictures_id'])) ? 'oui' : 'non' ?> </td>
                <td class="actions">
                    <a href="index.php?action=auth&q=galleryAdmin&opt=getOne&id=<?=$article['postId']?>" class="view"><i class="fas fa-eye fa-xs"></i></a>
                    <a href="index.php?action=auth&q=galleryAdmin&opt=edit&id=<?=$article['postId']?>" class="edit"><i class="fas fa-pen fa-xs"></i></a>
                    <a href="index.php?action=auth&q=galleryAdmin&opt=delete&id=<?=$article['postId']?>" class="trash"><i class="fas fa-trash fa-xs"></i></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<p class='back'><a href="index.php?action=auth" >Retour</a></p>
<script src="./assets/js/confirm.js"></script>