<form class="formAuth" action='' method='POST' accept-charset="UTF-8">
    <div class="formAuth__group">
        <label for="street">Modifier la rue : </label>
        <input type="text" value="<?=  $infos[0]['street'] ?>" name="street">
    </div>
    <div class="formAuth__group">
        <label for="city">Modifier la ville : </label>
        <input type="text" value="<?=  $infos[0]['city'] ?>" name="city">
    </div>
    <div class="formAuth__group">
        <label for="mail">Modifier l'adresse mail : </label>
        <input type="text" value="<?=  $infos[0]['mail'] ?>" name="mail">
    </div>
    <div class="formAuth__group">
        <label for="tel">Modifier le numéro : </label>
        <input type="text" value="<?=  $infos[0]['tel'] ?>" name="tel">
    </div>
    <div class="formAuth__group">
        <input type="submit" value="Modifier">
    </div>
</form>
<p class='back'><a href="index.php?action=auth">Retour</a></p>