<main class=pageAdmin>
    <h2>Espace d'administration</h2>
    <div class="pageAdmin__option">
        <a href="index.php?action=auth&q=contactAdmin"><p>Gérer les coordonnées</p></a>
        <a href="index.php?action=auth&q=testAdmin"><p>Gérer les "témoignages"</p></a>
        <a href="index.php?action=auth&q=servicesAdmin"><p>Gérer les "services"</p></a>
        <a href="index.php?action=auth&q=aboutAdmin"><p>Gérer les "à propos"</p></a>
        <a href="index.php?action=auth&q=imagesAdmin"><p>Gérer les images</p></a>
    </div>
</main>