<h2 class='title'><em>Rubrique <?php switch(substr($_GET['q'], 0, -5)): case "test": ?>témoignages<?php break; ?><?php case "about": ?>à propos<?php break; ?><?php default: ?>services<?php endswitch; ?></em> : Ici tu peux générer le contenu ou en modifier</h2>
<form action='' method='POST' accept-charset="UTF-8"  enctype="multipart/form-data">
    <fieldset class="formArticle">
        <textarea id="myTextarea" name='postCont'>
            <?php echo (isset($_GET['id'])) ?
            htmlspecialchars($article[0]['postCont']) : 
            '' ?></textarea>
        <p class="formArticle__error"><?php echo($data["error-cont"] ?? '') ?></p>
            
        <div class="formArticle__group">
            <div class="formArticle__group__loader">
                <label for="postImgName">Titre de la nouvelle image :</label>
                <input type='text' id="customSpace" name='postImgName' 
                    value='<?= (isset($_GET['id']) && isset($article[0]['postSrc'])) ? 
                    $article[0]['postImgName'] : '' ?>'>
                <input type="file" name="postSrc" id="inputFile" hidden="hidden">
            </div>
            <button id='inputFileButton' type="button" class="formArticle__group__btn">
                    Ajouter une nouvelle image (.png, .jpeg or .jpg) </button>
            <div class="formArticle__group__loader">
                <label for="imgName"> ou sélectionner une image :</label>
                <select name='imgName' id="imgNameSelected">
                    <option value="">Liste d'images</option>
                    <?php if(isset($pictures) && !empty($pictures)): ?>
                    <?php foreach($pictures as $key => $option): ?>
                    <?php if (isset($_GET['id']) && $option === $article[0]['postImgName']): ?>
                    <option value="<?php echo $option['url']; ?>" selected><?php echo $option['imgName']; ?></option>
                    <?php else: ?>
                    <option value="<?php echo $option['url']; ?>" ><?php echo $option['imgName']; ?></option>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
        </div>
        <p class="formArticle__error"><?php echo($data["error-file"] ?? '') ?></p>
        <img id='activimg' src='<?= (isset($_GET['id']) && isset($article[0]['postSrc'])) ?
                $article[0]['postSrc'] : '' ?>' alt='<?= (isset($_GET['id'])  && isset($article[0]['postSrc'])) ? 
                $article[0]['postImgName'] : '' ?>' />
        <div class="formArticle__author">
            <label for="postAuthor">Auteur : </label>
            <input type='text' name='postAuthor' value='<?= (isset($_GET['id'])) ?
                    $article[0]['postAuthor'] : '' ?>'>
            <p class="formArticle__error"><?php echo($data["error-author"] ?? '') ?></p>
            
            <input type='submit' name='submit' value='envoyer'>
        </div>
    </fieldset>
</form>

<p class="back"><a  href="index.php?action=auth&q=<?php echo $_GET['q'] ?>&opt=getAll">Retour</a></p>

<script src="./assets/js/picture.js"></script>