<h2 class="title">Le contenu pour la rubrique 
<?php switch(substr($_GET['q'], 0, -5)): case "test": ?>
des témoignages<?php break; ?><?php case "about": ?>des à propos<?php break; ?>
<?php case "welcome": ?>de la page d'accueil<?php break; ?>
<?php default: ?>des services<?php endswitch; ?></h2>
<p class="add"><a href="index.php?action=auth&q=<?= $_GET["q"]?>&opt=addArticle">Ajouter du contenu</a></p>
<table class="content" id="table">
    <thead>
        <tr>
            <th>Crée le</th>
            <th>Contenu</th>
            <th>Image</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($data['article']) && $data['article'] !== null): ?>
            <?php foreach ($data['article'] as  $article): ?>
            <tr>
                <td><?= $article['postDate']?></td>
                <td><?= substr($article['postCont'], 0, 100).'...'?></td>
                <td><?= (isset($article['tb_pictures_id'])) ? 'oui' : 'non' ?> </td>
                <td class="actions">
                    <a href="index.php?action=auth&q=<?= $_GET["q"]?>&opt=getOne&id=<?=$article['postId']?>" class="view"><i class="fas fa-eye fa-xs"></i></a>
                    <a href="index.php?action=auth&q=<?= $_GET["q"]?>&opt=edit&id=<?=$article['postId']?>" class="edit"><i class="fas fa-pen fa-xs"></i></a>
                    <a href="index.php?action=auth&q=<?= $_GET["q"]?>&opt=delete&id=<?=$article['postId']?>" onclick="return confirm('Are you sure ?')" class="trash"><i class="fas fa-trash fa-xs"></i></a>
                </td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>
<p class='back'><a href="index.php?action=auth">Retour</a></p>