<header class="header">
    <h1 class="header__h1">Connexion</h1>
</header>
<main class="page page--auth">
    <form method='POST' class="form"> 
        <fieldset class="formAuth">
            <legend class="formAuth__legend">Se connecter</legend> 
            <p class="formAuth__error"><?php echo($data["error-connect"] ?? '') ?></p>
            <div class="formAuth__group">
                <label for="email">L'e-mail</label>
                <input type="text" name="email"/> 
                <p class="formAuth__error"> <?php echo($data["error-email"] ?? '') ?> </p>
            </div>
            <div class="formAuth__group">
                <label for="pass">Le mot de passe</label>
                <input type="password" name="pass"/> 
                <p class="formAuth__error"> <?php echo($data["error-pwd"] ?? '') ?> </p>
            </div>
            <div class="formAuth__group">
                <input type="hidden" name="form" value='Connexion'> 
                <input type="submit" value="Connexion"/>
            </div>
            <span><a href="index.php?action=Welcome">Continuer sans se connecter</a></span>
        </fieldset>
    </form>
</main>
  